### ISSUE TITLE
unstable ipsec connection with opportunistic group and ikev2

### ISSUE THREAD

**Issue by yuanlinios** [libreswan/libreswan#185]
#### Description
set up ipsec with opportunistic group among several centos hosts, but the ipsec connection get interrupted from time to time.

##### Version
centos 7.4.1708 x86_64
libreswan-3.23-3.el7.x86_64

##### Configuration
The setup mainly refers to https://docs.openshift.com/container-platform/3.9/admin_guide/ipsec.html

/etc/ipsec.conf
```
config setup
        protostack=netkey
        dumpdir=/var/run/pluto/
        virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:25.0.0.0/8,%v4:100.64.0.0/10,%v6:fd00::/8,%v6:fe80::/10
include /etc/ipsec.d/*.conf
```

/etc/ipsec.d/lab.conf
```
conn private
  left=%defaultroute
  leftid=%fromcert
  leftcert="NSS Certificate DB:*.lab.local - LAB"
  right=%opportunisticgroup
  rightid=%fromcert
  rightca=%same
  ikev2=insist
  authby=rsasig
  failureshunt=drop
  negotiationshunt=hold
  auto=ondemand
  dpddelay=1
  dpdtimeout=3
  dpdaction=restart

conn clear
  left=%defaultroute
  right=%group
  authby=never
  type=passthrough
  auto=route
  priority=100
```

/etc/ipsec.d/policies/private
```
10.65.150.34/32
10.65.150.35/32
10.65.150.40/32
10.65.150.41/32
10.65.150.42/32
10.65.150.43/32
10.65.150.46/32
10.65.150.47/32
10.65.150.48/32
10.65.150.49/32
```

other policy files are empty (clear, block, clear-or-private, private-or-clear)
all hosts have the same configuration

```
ipsec verify
Verifying installed system and configuration files

Version check and ipsec on-path                         [OK]
Libreswan 3.23 (netkey) on 3.10.0-693.21.1.el7.x86_64
Checking for IPsec support in kernel                    [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                    [OK]
         ICMP default/accept_redirects                  [OK]
         XFRM larval drop                               [OK]
Pluto ipsec.conf syntax                                 [OK]
Two or more interfaces found, checking IP forwarding    [OK]
Checking rp_filter                                      [OK]
Checking that pluto is running                          [OK]
 Pluto listening for IKE on udp 500                     [OK]
 Pluto listening for IKE/NAT-T on udp 4500              [OK]
 Pluto ipsec.secret syntax                              [OK]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]
Checking 'prelink' command does not interfere with FIPS [OK]
Checking for obsolete ipsec.conf options                [OK]
```

##### Additional Information
The setup works at beginning. Each host can reach/ping others successfully
```
ipsec whack --trafficstatus
006 #2: "private#10.65.150.34/32"[1] ...10.65.150.34, type=ESP, add_time=1528855752, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #4: "private#10.65.150.35/32"[1] ...10.65.150.35, type=ESP, add_time=1528855756, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #6: "private#10.65.150.40/32"[1] ...10.65.150.40, type=ESP, add_time=1528855760, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #8: "private#10.65.150.42/32"[1] ...10.65.150.42, type=ESP, add_time=1528855767, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #10: "private#10.65.150.43/32"[1] ...10.65.150.43, type=ESP, add_time=1528855769, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #12: "private#10.65.150.46/32"[1] ...10.65.150.46, type=ESP, add_time=1528855771, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #14: "private#10.65.150.47/32"[1] ...10.65.150.47, type=ESP, add_time=1528855772, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #16: "private#10.65.150.48/32"[1] ...10.65.150.48, type=ESP, add_time=1528855773, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #18: "private#10.65.150.49/32"[1] ...10.65.150.49, type=ESP, add_time=1528855775, inBytes=588, outBytes=588, id='O=LAB, CN=*.lab.local'
```

But after several hours, some hosts fail to reach some others

For example, 10.65.150.41 fails to ping 10.65.150.43 and 10.65.150.49
```
ping -c4 10.65.150.43
PING 10.65.150.43 (10.65.150.43) 56(84) bytes of data.

--- 10.65.150.43 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 2999ms

ping -c4 10.65.150.49
PING 10.65.150.49 (10.65.150.49) 56(84) bytes of data.

--- 10.65.150.49 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 2999ms
```

from 10.65.150.41:
```
ipsec whack --trafficstatus
...
006 #10: "private#10.65.150.43/32"[1] ...10.65.150.43, type=ESP, add_time=1528869077, inBytes=0, outBytes=588, id='O=LAB, CN=*.lab.local'
006 #12: "private#10.65.150.49/32"[1] ...10.65.150.49, type=ESP, add_time=1528869086, inBytes=0, outBytes=588, id='O=LAB, CN=*.lab.local'
```

from 10.65.150.43:
```
ipsec whack --trafficstatus
006 #4: "private#10.65.150.41/32"[2] ...10.65.150.41, type=ESP, add_time=1528869077, inBytes=0, outBytes=0, id='O=LAB, CN=*.lab.local'
```

from 10.65.150.49:
```
ipsec whack --trafficstatus
006 #10: "private#10.65.150.41/32"[2] ...10.65.150.41, type=ESP, add_time=1528869086, inBytes=0, outBytes=0, id='O=LAB, CN=*.lab.local'
```

But ping 10.65.150.41 from 10.65.150.43 and 10.65.150.49 is successful. And after that, 10.65.150.41 can ping the other two again.

Any idea about this issue?

**Comment by logachev** [comment]
I see very similar issue.
In my scenario I have 2 hosts with existing tunnel A<->B.
Everything works fine until you restart ipsec service at one host, lets say B (to emulate the crash).

When B is back up, seems like A fails to recreate the tunnel. 
A -> B -- doesn't work (just a ping)
If I try B -> A, it successfully recreates A<->B tunnel and traffic goes either direction.

Any ideas on why this is failing?

**Comment by letoams** [comment]
We would need to see the logs to determine what is happening

**Comment by logachev** [comment]
@letoams Can you share what logs you need and how to collect them? 

I believe I was trying to see what's going on with 'ipsec barf' but logs were empty (host A didn't try to recreate the tunnel..)

**Comment by letoams** [comment]
Best is to use logfile=/var/log/pluto.log in ipsec.conf to avoid rate limits of syslog.

We can try regular loglevel or you can just bump it to plutodebug=all (which still doesn’t log any private keys)

**Comment by logachev** [comment]
I found the problem with my scenario: I wasn't patient enough.
In my case, tunnel was always restored after 5 minutes.. Sometimes it happened in a few seconds or 1-2 minutes. 

The problem appeared to be in xfrmlifetime. I missed the fact that this timeframe is tight to the connection creation time, not connection lost event.

I'm sorry for this confusion.

**Comment by letoams** [comment]
On Tue, 10 Jul 2018, Kirill Logachev wrote:

> I found the problem with my scenario: I wasn't patient enough.
> In my case, tunnel was always restored after 5 minutes.. Sometimes it happened in a few seconds or 1-2 minutes.
> 
> The problem appeared to be in xfrmlifetime. I missed the fact that this timeframe is tight to the connection creation time, not connection lost event.

I disagree. If an idle tunnel is torn down, a new one should come up
based on a new packet trigger. If the tunnel is not idle then it should
not be torn down. Regardless, packetflow should always work.

So I'm still very much interested in what is happening for you.

Paul

**Comment by logachev** [comment]
Here's a configuration I have right now (this is really a playground, so I can make any changes you offer, removed comments from the output).

`xfrmlifetime=60` -- this is to collect logs faster.

I placed pluto.log file here: https://1drv.ms/u/s!Ak3YaXY0zFpXjslHOe279MIcw5rh0w
It has also ping.log file -- it was the only thing trying to reach out remote host with IP `10.0.0.6`.
As you can see, it was restored every ~60 seconds.

In the `pluto.log file` -- connection is restored immediately after `netlink_get: XFRM_MSG_EXPIRE message`

``` bash
[root@kiril710-000001 kiril]# cat /etc/ipsec.conf
config setup
        logfile=/var/log/pluto.log
        plutodebug="all"
        xfrmlifetime=60
        virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:25.0.0.0/8,%v4:100.64.0.0/10,%v6:fd00::/8,%v6:fe80::/10

include /etc/ipsec.d/*.conf

[root@kiril710-000001 kiril]# cat /etc/ipsec.d/private_ipsec.conf
conn private
        type=tunnel
        left=%defaultroute
        leftid=%fromcert
        leftcert="NSS Certificate DB:kiril710-000001"
        right=%opportunisticgroup
        rightid=%fromcert
        rightca=%same
        ikev2=insist
        authby=rsasig
        failureshunt=drop
        negotiationshunt=hold
        dpdaction=restart
        auto=ondemand
        dpddelay=1
        dpdtimeout=3

conn clear
        left=%defaultroute
        right=%group
        type=passthrough
        auto=route

[root@kiril710-000001 kiril]# cat /etc/ipsec.d/policies/private
10.0.0.0/24
```

**Comment by rbdunne** [comment]
Here is the relevant pluto.log info from where our tunnel went down...
Timeline
--------
mco ping from fw to ui0  good at 16:25:47
mco ping from fw to ui0  failed by 16:26:52
mco ping from fw to ui0  recovered by 16:29:03


Pluto log at admin host (10.11.165.107 is ui0 IP)
-------------------------------------------------
Sep  7 16:26:41.647262: "private-or-clear#10.11.165.107/32"[1] ...10.11.165.107 #21: ESP traffic information: in=0B out=1MB
Sep  7 16:26:41.663603: expire unused parent SA #18 "private-or-clear#10.11.165.107/32"[1] ...10.11.165.107
Sep  7 16:26:41.663706: "private-or-clear#10.11.165.107/32"[1] ...10.11.165.107 #18: received delete request for PROTO_v2_ESP SA(0xedd92394) but corresponding state not found
Sep  7 16:26:41.663726: "private-or-clear#10.11.165.107/32"[1] ...10.11.165.107 #18: ISAKMP SA expired (LATEST!)
Sep  7 16:26:41.663733: "private-or-clear#10.11.165.107/32"[1] ...10.11.165.107 #18: deleting state (STATE_PARENT_I3) and sending notification
Sep  7 16:26:41.664234: packet from 10.11.165.107:500: ISAKMP_v2_INFORMATIONAL message response has no matching IKE SA
...
Sep  7 16:27:46.643249: "private-or-clear#10.11.165.107/32"[1] ...10.11.165.107 #19: received Delete SA payload: delete IPSEC State #22 now
Sep  7 16:27:46.643278: "private-or-clear#10.11.165.107/32"[1] ...10.11.165.107 #22: ESP traffic information: in=4MB out=0B


Pluto log at ui0 host (10.11.174.224 is admin IP)
-------------------------------------------------
Sep  7 16:26:41.623102: "private-or-clear#10.11.174.224/32"[1] ...10.11.174.224 #2: received Delete SA payload: delete IPSEC State #4 now
Sep  7 16:26:41.623200: "private-or-clear#10.11.174.224/32"[1] ...10.11.174.224 #4: ESP traffic information: in=1MB out=0B
...
Sep  7 16:27:46.618370: "private-or-clear#10.11.174.224/32"[1] ...10.11.174.224 #3: ESP traffic information: in=0B out=4MB
Sep  7 16:27:46.637610: expire unused parent SA #1 "private-or-clear#10.11.174.224/32"[1] ...10.11.174.224
Sep  7 16:27:46.637696: "private-or-clear#10.11.174.224/32"[1] ...10.11.174.224 #1: received delete request for PROTO_v2_ESP SA(0xdb0ad661) but corresponding state not found
Sep  7 16:27:46.637715: "private-or-clear#10.11.174.224/32"[1] ...10.11.174.224 #1: ISAKMP SA expired (LATEST!)
Sep  7 16:27:46.637722: "private-or-clear#10.11.174.224/32"[1] ...10.11.174.224 #1: deleting state (STATE_PARENT_I3) and sending notification
Sep  7 16:27:46.638328: packet from 10.11.174.224:500: ISAKMP_v2_INFORMATIONAL message response has no matching IKE SA

**Comment by letoams** [comment]
This looks like a bug in /32 group policies. We are working on fix.
As a workaround try using at least /30 entries for the /etc/ipsec.d/policies files for now

**Comment by letoams** [comment]
we have a patch that should go into 3.28

**Comment by slesru** [comment]
Hello!

Is it possible to apply this patch to 3.25, which is shipped with rhel 7 and centos 7 ?
If yes, could you tell me how can I get it?

Thank you!

**Comment by letoams** [comment]
On Thu, 7 Mar 2019, slesru wrote:

> Is it possible to apply this patch to 3.25, which is shipped with rhel 7 and centos 7 ?
> If yes, could you tell me how can I get it?

Our testing found this patch is not fully ready yet. If we get an
improved patch, I will do a 3.28rc1 build for rhel7/centos7 that
you can use by enabling the libreswan repo from:

https://download.libreswan.org/binaries/rhel/7/libreswan-release-7-1.noarch.rpm

Paul

**Comment by bscholtes** [comment]
Hi,

as of rhel7 we use libreswan-3.25-4.8.el7_6.x86_64 
but still have similar problems.

I saw  
https://download.libreswan.org/binaries/rhel/7/x86_64/libreswan-3.29-1.el7.x86_64.rpm
is available. Does this version fix the issue ?

Bernhard

**Comment by letoams** [comment]
On Fri, 28 Jun 2019, bscholtes wrote:

> as of rhel7 we use libreswan-3.25-4.8.el7_6.x86_64
> but still have similar problems.
> 
> I saw
> https://download.libreswan.org/binaries/rhel/7/x86_64/libreswan-3.29-1.el7.x86_64.rpm
> is available. Does this version fix the issue ?

No, but you can grab the source rpm from there and apply this patch:

https://github.com/libreswan/libreswan/commit/24bffe6702e8a3a9cfc230c9bacc43fef9da204b

Paul

**Comment by fnoorden-vs** [comment]
Is this problem solved in versions later then 3.29?

Frank

**Comment by letoams** [comment]
On Tue, 28 Apr 2020, fnoorden-vs wrote:

> Is this problem solved in versions later then 3.29?

It is greatly improved upon in 3.31, and some more in git master.
We still see an issue sometimes about double shunts that I'm
still investigating.

Paul

**Comment by oddsyntax** [comment]
Jumping in here to make sure I get updates, because this double shunt issue you mentioned is exactly what I'm troubleshooting in a setup. I've found that in 99% of the cases, running the command "ipsec whack --crash $IP" is restoring connectivity, but surely there's a better way to do this. I did find that my ipsec verify is warning about ICMP send/receive redirects and rp_filter, but otherwise is "OK". I also found that I have a lot of "XfrmInStateSeqError" from before I disabled replay-window, but still see some issues with connectivity.

Michelle

**Comment by letoams** [comment]
On Thu, 21 May 2020, Michelle Ryals wrote:

> Jumping in here to make sure I get updates, because this double shunt issue you mentioned is exactly what I'm troubleshooting in a setup. I've found that in 99%
> of the cases, running the command "ipsec whack --crash $IP" is restoring connectivity, but surely there's a better way to do this. I did find that my ipsec verify
> is warning about ICMP send/receive redirects and rp_filter, but otherwise is "OK". I also found that I have a lot of "XfrmInStateSeqError" from before I disabled
> replay-window, but still see some issues with connectivity.

This is still on my TODO list to look at. You are not the only one
affected.

Paul

**Comment by cagney** [comment]
mainline (which will eventually turn into 5.0) has overhauled how overlapping shunts (kernel policies) are handled.
Please try mainline or 5.0 and let us know.
