### ISSUE TITLE
isa_length uninitialized in programs/pluto/ikev2_parent.c:6291

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#214]
on [debian's ia64 build daemon](https://buildd.debian.org/status/fetch.php?pkg=libreswan&arch=ia64&ver=3.27-1&stamp=1539383694&raw=0), we see a build warning that is treated as an error: 

```
/<<PKGBUILDDIR>>/programs/pluto/ikev2_parent.c: In function 'process_encrypted_informational_ikev2':
/<<PKGBUILDDIR>>/programs/pluto/ikev2_parent.c:6291:4: error: missing initializer for field 'isa_length' of 'struct isakmp_hdr' [-Werror=missing-field-initializers]
    };
    ^
In file included from /<<PKGBUILDDIR>>/programs/pluto/packet.h:274,
                 from /<<PKGBUILDDIR>>/programs/pluto/pluto_x509.h:25,
                 from /<<PKGBUILDDIR>>/programs/pluto/ikev2_parent.c:50:
/<<PKGBUILDDIR>>/programs/pluto/isakmp_hdr.h:55:11: note: 'isa_length' declared here
  uint32_t isa_length; /* Length of message */
           ^~~~~~~~~~
cc1: all warnings being treated as errors
```

note that elsewhere in that same file, a header has `isa_length` initialized to 0 -- i'm not sure that works the same way here, but it probably ought to be handled explicitly.

**Comment by letoams** [comment]
These are fixed in master already? Or did you somehow got a different one ?

**Comment by dkg** [comment]
this is from the build of 3.27 -- and yes, i do see the fix from master in 16859c49e67903a913e38f6410718f6b42647a89 (though i don't understand how `filled in on pbs close` makes sense as a comment there, given that `hdr` is about to fall out of scope).  I'll pull the change from upstream.

**Comment by dkg** [comment]
i still don't understand that comment, but the fix seems to let the build go through, so i'll close this ticket.
